- .github/workflows/code-check.yml
- README.md
- package-lock.json
- package.json
- src/commands/clearCommand.ts
- src/commands/commands.ts
- src/commands/endCommand.ts
- src/commands/helpCommand.ts
- src/commands/startCommand.ts
- src/processor/codeBlockProcessor.ts
- src/processor/emojiProcessor.ts
- src/processor/guildEmojiProcessor.ts
- src/processor/maxLengthProcessor.ts
- src/processor/urlProcessoor.ts
- src/speaker/speaker.ts
- src/speaker/voiceroidSpeaker.ts
github-actionsでpush / PR時に
1. `yarn install` - インストール
2. `yarn run check` - コードチェック
3. `yarn run build` - ビルド
を実行するよう設定した
> linterとformatterを導入した

- .eslintrc.js
- docker-compose.yml
- package-lock.json
- package.json
#5 を修正した
ただeslintから大量の怒られが発生しているので，気が向いたら修正しといてちょ
```log
yarn run v1.22.10
$ eslint src/**/*.ts
/Users/abelab/typescript/yosuga-bot/src/commands/clearCommand.ts
8:43  warning  'config' is defined but never used  @typescript-eslint/no-unused-vars
/Users/abelab/typescript/yosuga-bot/src/commands/commands.ts
31:23  warning  Missing return type on function                         @typescript-eslint/explicit-module-boundary-types
45:32  warning  Missing return type on function                         @typescript-eslint/explicit-module-boundary-types
49:31  warning  Missing return type on function                         @typescript-eslint/explicit-module-boundary-types
57:30  warning  Missing return type on function                         @typescript-eslint/explicit-module-boundary-types …
```
> [chore] eslintrcの設定ファイルを作成

- src/processor/urlProcessoor.ts
> fix: #7の修正

- src/configManager.ts
- src/processor/urlProcessor.ts
- src/sessionHandler/message.ts
- src/speechQueue.ts
- src/types.ts
> URLの読み上げを改善

- src/commandManager.ts
> fix: これが原因でスラッシュコマンドの返信が返ってこない可能性

- src/speaker/voiceroidDaemonSpeaker.ts
> fix: voiceroidDaemonSpeakerにタイムアウト追加

- src/commands/voiceStatusCommand.ts
- src/speaker/voiceProvider.ts
> fix: voiceが登録されていない状態でvoice-statusを読んだ際は警告を出すように

- src/speaker/voicevoxSpeaker.ts
> fix:VOICEVOXの話者テストを話者の存在確認だけに省略

- src/handler/base/sessionContextHandler.ts
- src/handler/filter/sessionFilter.ts
- src/handler/session/autoLeaveHandler.ts
- src/handler/session/noticeEnterChannelHandler.ts
- src/handler/session/noticeLeaveChannelHandler.ts
- src/handler/session/noticeTurnOnCameraHandler.ts
- src/handler/session/noticeTurnOnGoLiveHandler.ts
- src/handler/session/readOutMessageHandler.ts
>  sessionFilterが掛かっていなかった不具合を修正

- src/handler/filter/turnOnCameraFilter.ts
- src/handler/session/noticeTurnOnCameraHandler.ts
- src/handler/session/noticeTurnOnGoLiveHandler.ts
> GoLive開始が読み上げられていないのを修正

- src/speaker/voicevoxSpeaker.ts
> VOICEVOXのSpeakerチェックで/audio_queryも見るように変更

- src/commandContext.ts
- src/commandContextSlash.ts
- src/handler/base/commandHandler.ts
- src/handler/base/setConfigSubCommandHandler.ts
- src/handler/command/clearCommand.ts
- src/handler/command/configSub/setAutoLeaveSecSub.ts
- src/handler/command/configSub/setFastSpeedSub.ts
- src/handler/command/configSub/setMaxLengthSub.ts
- src/handler/command/configSub/setReadNameIntervalSub.ts
- src/handler/command/configSub/setSpeedSub.ts
- src/handler/command/configSub/setVoiceSub.ts
- src/handler/command/configSub/setVolumeSub.ts
- src/handler/command/configSub/showConfigSub.ts
- src/handler/command/endCommand.ts
- src/handler/command/startCommand.ts
- src/handler/command/versionCommand.ts
- src/handler/command/voiceStatusCommand.ts
- src/handler/handlerLoader.ts
- src/util/promiseUtil.ts
- src/util/range.test.ts
- src/util/range.ts
> /user-config voiceコマンドをインタラクティブに

- src/commandContextSlash.ts
> showサブコマンドでエラーが発生していたのを修正

- src/handler/session/readOutMessageHandler.ts
> fix: urlが文字数制限で切られてしまうのを修正

- src/handler/session/autoLeaveHandler.ts
> fix: 自動退出タイマー中に別チャンネルに移動したときの挙動がおかしかったのを修正

- src/handler/command/testCommand.ts
- src/inquirer/component/componentHook.ts
- src/inquirer/component/componentHookWithValue.ts
- src/inquirer/component/modalText.ts
- src/inquirer/component/multiSelect.ts
- src/inquirer/component/pagedSelect.ts
- src/inquirer/component/singleSelect.ts
- src/inquirer/promptController.ts
- src/inquirer/wrapper/createSelectMenu.ts
- src/util/replyHelper.ts
- pagedSelectを実装
- ephemeralが機能していなかったバグを修正
- selectの下限上限が正しく無かったのを修正
- selectOptionのdefaultパラメータをlazyからbooleanに
> ページングされたSelectコンポーネントを追加

- src/inquirer/component/pagedSelect.ts
- src/inquirer/component/pagedSingleSelect.ts
- src/inquirer/component/select.ts
- src/inquirer/component/singleSelect.ts
- src/inquirer/promptController.ts
> 単独選択のページング付きSelectコンポーネントを実装

- src/util/eventFlow.test.ts
- src/util/eventFlow.ts
filterを高階関数っぽく掛けられるEventEmitter
> EventFlowシステムを実装

- .husky/pre-commit
- package-lock.json
- package.json
eslintとprettierの--cache使えば速度そんなに変わらなそう
> chore: lint-stagedを削除

- src/util/replyHelpter.ts
> chore: discordjsを13の最新にアップデート
